### ISSUE TITLE
Is there is any callback to fetch only Indian stocks?

### ISSUE THREAD

**Issue by deepthik-r** [theBoyMo/market-data-tracker#1]
Hi,
Currently Iam using, "http://autoc.finance.yahoo.com/autoc?query=infos&callback=YAHOO.Finance.SymbolSuggest.ssCallback&region=INDIA&lang=en-US, tag=null} " to retire stocks.

But my stockExchange fectched from YahooFinance is not Indian stock exchange.
Is there any way to get only Indian Stocks?

**Comment by TheBoyMoe** [comment]
Hi deepthik-r
I'm afraid I don't know. I used the finance quotes api simply because it was an easy way to interact with the Yahoo Finance data and import it into the app with minimum fuss. As to your partiicular request you would have to check there documentation at https://financequotes-api.com/.

Hope that helps

Bill
